### Refresh Token
POST http://localhost:3000/refresh-token
Content-Type: application/json

{
  "token": "{\"sub\":\"c9246ae5-c8ac-4887-a2b6-6e5aa1a4361e\",\"email\":\"gaby@airsoftpro.com\",\"playerName\":\"gabyludo\",\"roles\":[\"PLAYER\"],\"code\":\"321\"}"
}

###