### Refresh Token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "token": "{\"sub\":\"e8949779-2af0-46b8-87fd-f9114ce223de\",\"email\":\"gaby@airsoftpro.com\",\"playerName\":\"gabyludo\",\"roles\":[\"PLAYER\"],\"code\":\"321\"}"
}

###