import 'reflect-metadata';
import request from 'supertest';
import { ExpressAdapter } from '@/infrastructure/express-adapter';
import container from '@/infrastructure/container';
import PlayerController from '@/infrastructure/controllers/player-controller';
import UserController from '@/infrastructure/controllers/user-controller'; // Or AuthController if preferred for user creation
import * as Constants from '@/shared/constants/constants';

// Repositories
import { IPlayerRepository } from '@/application/repositories/player-repository';
import { IUserRepository } from '@/application/repositories/user-repository';
import { IReportRepository } from '@/application/repositories/report-repository';
import PlayerRepositoryMemory from '@/infrastructure/repositories/player-repository-memory';
import UserRepositoryMemory from '@/infrastructure/repositories/user-repository-memory';
import ReportRepositoryMemory from '@/infrastructure/repositories/report-repository-memory';

// Entities & Enums
import { Player } from '@/domain/entities/player';
import { User } from '@/domain/entities/user';
import { Report } from '@/domain/entities/report';
import { ReportMotivation } from '@/domain/enums/report-motivation';

// DTOs
interface CreatePlayerDto {
  userId: string;
  name: string;
  motto: string;
}

// --- Helper Functions ---
const createTestUser = (id: string, emailSuffix: string = ''): User => {
  const user = new User(`Test User ${id}`, `test-player-user-${id}${emailSuffix}@example.com`, 'password123', new Date(1990, 1, 1), `photo-${id}.jpg`);
  user.id = id;
  return user;
};

const createTestPlayer = async (user: User, name: string, motto: string, playerRepo: IPlayerRepository): Promise<Player> => {
  const player = new Player(user.id, name, motto, 0, [], [], false, new Date(), new Date());
  // In a real scenario, player ID might be different from user ID or generated upon creation.
  // For testing, we might align them or use a specific known ID if the use case allows/expects it.
  // Here, assuming player.id is generated by repository or use case.
  const createdPlayer = await playerRepo.create(player); // This will assign an ID
  return createdPlayer;
};

const createTestReport = async (fromPlayerId: string, toPlayerId: string, gameId: string, motivation: ReportMotivation, reportRepo: IReportRepository): Promise<Report> => {
  const report = new Report(fromPlayerId, toPlayerId, gameId, motivation, `Description for report from ${fromPlayerId} to ${toPlayerId}`);
  // report.id will be set by repository
  const createdReport = await reportRepo.create(report);
  return createdReport;
};


describe('PlayerController - Player and Reports E2E Tests', () => {
  let app: ExpressAdapter;
  let playerRepository: IPlayerRepository;
  let userRepository: IUserRepository;
  let reportRepository: IReportRepository;
  let baseUser: User; // A user to be used for creating players

  beforeEach(async () => {
    const testContainer = container.createChildContainer();

    app = new ExpressAdapter();
    testContainer.register(Constants.HTTP, { useValue: app });

    userRepository = new UserRepositoryMemory();
    playerRepository = new PlayerRepositoryMemory();
    reportRepository = new ReportRepositoryMemory();

    testContainer.register(Constants.USER_REPOSITORY, { useValue: userRepository });
    testContainer.register(Constants.PLAYER_REPOSITORY, { useValue: playerRepository });
    testContainer.register(Constants.REPORT_REPOSITORY, { useValue: reportRepository });

    testContainer.resolve(PlayerController);
    // Resolve UserController or AuthController if user creation is through API in setup
    // For now, creating users directly in repo.
    // testContainer.resolve(UserController);

    baseUser = createTestUser('baseUserForPlayerTests');
    await userRepository.create(baseUser);
  });

  describe('POST /players (Create Player)', () => {
    it('should create a new player successfully', async () => {
      const playerData: CreatePlayerDto = {
        userId: baseUser.id,
        name: 'CoolPlayer123',
        motto: 'Play hard, have fun!',
      };

      const response = await request(app.getInstance())
        .post('/players')
        .send(playerData);

      expect(response.status).toBe(201);
      expect(response.body.player).toBeDefined();
      expect(response.body.player.name).toBe(playerData.name);
      expect(response.body.player.motto).toBe(playerData.motto);
      expect(response.body.player.userId).toBe(baseUser.id);

      const createdPlayer = await playerRepository.findByUserId(baseUser.id);
      expect(createdPlayer).toBeDefined();
      expect(createdPlayer?.name).toBe(playerData.name);
    });

    it('should return 400 for missing required fields (e.g., name)', async () => {
      const playerData = { // Missing name
        userId: baseUser.id,
        motto: 'A motto needs a name.',
      };
      const response = await request(app.getInstance())
        .post('/players')
        .send(playerData);
      expect(response.status).toBe(400); // Or 422
    });

    it('should return 404 if userId is invalid (USER_NOT_FOUND)', async () => {
      const playerData: CreatePlayerDto = {
        userId: 'non-existent-user-id',
        name: 'GhostPlayer',
        motto: 'Seeking a user.',
      };
      const response = await request(app.getInstance())
        .post('/players')
        .send(playerData);
      expect(response.status).toBe(404);
    });

    it('should return 400 if player name already exists', async () => {
      // First, create a player with a specific name
      await createTestPlayer(baseUser, 'ExistingName', 'Original Motto', playerRepository);

      // Then, try to create another player with the same name but different user
      const anotherUser = createTestUser('anotherUser', 'unique');
      await userRepository.create(anotherUser);

      const playerData: CreatePlayerDto = {
        userId: anotherUser.id,
        name: 'ExistingName', // Same name
        motto: 'Trying to take a name.',
      };
      const response = await request(app.getInstance())
        .post('/players')
        .send(playerData);
      expect(response.status).toBe(400); // Or 409 (Conflict)
    });

    it('should return 400 if user already has a player profile', async () => {
      // First, create a player profile for baseUser
      await createTestPlayer(baseUser, 'PlayerProfile1', 'My first profile', playerRepository);

      // Then, try to create another player profile for the SAME baseUser
      const playerData: CreatePlayerDto = {
        userId: baseUser.id, // Same user
        name: 'PlayerProfile2',
        motto: 'My second attempt.',
      };
      const response = await request(app.getInstance())
        .post('/players')
        .send(playerData);
      expect(response.status).toBe(400); // Or 409 (Conflict)
    });
  });

  // GET /players/verify-name tests will be added next
  describe('GET /players/verify-name', () => {
    it('should return true for an available name', async () => {
      const response = await request(app.getInstance()).get('/players/verify-name?name=UniqueName123');
      expect(response.status).toBe(200);
      expect(response.body).toBe(true);
    });

    it('should return false for a taken name', async () => {
      await createTestPlayer(baseUser, 'TakenName', 'Motto', playerRepository);
      const response = await request(app.getInstance()).get('/players/verify-name?name=TakenName');
      expect(response.status).toBe(200);
      expect(response.body).toBe(false);
    });

    it('should return 400 if name query param is missing', async () => {
      const response = await request(app.getInstance()).get('/players/verify-name');
      // The controller implementation for verify-name has: if (!name) return false;
      // This means it would return 200 and false.
      // To expect 400, the controller would need to throw an error for missing param.
      // Adjusting expectation based on current controller logic.
      expect(response.status).toBe(200);
      expect(response.body).toBe(false);
      // If strict validation (e.g. 400 for missing param) is desired, controller needs change.
    });
  });

  // GET /players/:playerId/reports/given tests will be added next
  describe('GET /players/:playerId/reports/given', () => {
    let reportingPlayer: Player;
    let reportedPlayer: Player;

    beforeEach(async () => {
      const user1 = createTestUser('user1ForReports', 'given1');
      await userRepository.create(user1);
      reportingPlayer = await createTestPlayer(user1, 'ReportingPlayer', 'I report things', playerRepository);

      const user2 = createTestUser('user2ForReports', 'given2');
      await userRepository.create(user2);
      reportedPlayer = await createTestPlayer(user2, 'ReportedPlayer', 'I get reported', playerRepository);
    });

    it('should return an array of reports given by the player', async () => {
      await createTestReport(reportingPlayer.id, reportedPlayer.id, 'game1', ReportMotivation.CHEATING, reportRepository);
      await createTestReport(reportingPlayer.id, 'anotherPlayerId', 'game2', ReportMotivation.OFFENSIVE_BEHAVIOR, reportRepository);

      const response = await request(app.getInstance()).get(`/players/${reportingPlayer.id}/reports/given`);
      expect(response.status).toBe(200);
      expect(response.body).toBeInstanceOf(Array);
      expect(response.body.length).toBe(2);
      expect(response.body.every((r: Report) => r.from === reportingPlayer.id)).toBeTruthy();
    });

    it('should return an empty array if the player has given no reports', async () => {
      const response = await request(app.getInstance()).get(`/players/${reportingPlayer.id}/reports/given`);
      expect(response.status).toBe(200);
      expect(response.body).toEqual([]);
    });

    it('should return 404 if playerId is non-existent', async () => {
      const response = await request(app.getInstance()).get('/players/non-existent-player-id/reports/given');
      // This depends on how ViewGivenReportsHistory handles PlayerNotFound.
      // If it throws PlayerNotFound and that's mapped to 404 by an error handler.
      expect(response.status).toBe(404);
    });
  });

  // GET /players/:playerId/reports/received tests will be added next
  describe('GET /players/:playerId/reports/received', () => {
    let reportingPlayer: Player;
    let reportedPlayer: Player;

    beforeEach(async () => {
      const user1 = createTestUser('user1ForReportsRx', 'rx1');
      await userRepository.create(user1);
      reportingPlayer = await createTestPlayer(user1, 'ReportingPlayerRx', 'I report things Rx', playerRepository);

      const user2 = createTestUser('user2ForReportsRx', 'rx2');
      await userRepository.create(user2);
      reportedPlayer = await createTestPlayer(user2, 'ReportedPlayerRx', 'I get reported Rx', playerRepository);
    });

    it('should return an array of reports received by the player', async () => {
      await createTestReport(reportingPlayer.id, reportedPlayer.id, 'game1', ReportMotivation.CHEATING, reportRepository);
      await createTestReport('anotherPlayerId', reportedPlayer.id, 'game2', ReportMotivation.TOXICITY, reportRepository);

      const response = await request(app.getInstance()).get(`/players/${reportedPlayer.id}/reports/received`);
      expect(response.status).toBe(200);
      expect(response.body).toBeInstanceOf(Array);
      expect(response.body.length).toBe(2);
      expect(response.body.every((r: Report) => r.to === reportedPlayer.id)).toBeTruthy();
    });

    it('should return an empty array if the player has received no reports', async () => {
      const response = await request(app.getInstance()).get(`/players/${reportedPlayer.id}/reports/received`);
      expect(response.status).toBe(200);
      expect(response.body).toEqual([]);
    });

    it('should return 404 if playerId is non-existent', async () => {
      const response = await request(app.getInstance()).get('/players/non-existent-player-id/reports/received');
      // This depends on how ViewReceivedReportsHistory handles PlayerNotFound.
      expect(response.status).toBe(404);
    });
  });
});
